create table t_answer (
    id int8 generated by default as identity,
    answer varchar(255),
    question_id int8 not null,
    primary key (id));

create table t_branch (
    id int8 generated by default as identity,
    title varchar(255),
    primary key (id));

create table t_question (
    id int8 generated by default as identity,
    answer varchar(255),
    question varchar(255),
    branch_id int8 not null,
    primary key (id));

alter table if exists t_answer add constraint FK2yeu0mh3hebrr3w78q9cy27rw foreign key (question_id) references t_question on delete cascade;
alter table if exists t_question add constraint FKienswot30xhkcvwba87g77urp foreign key (branch_id) references t_branch on delete cascade;